apiVersion: v1
kind: PersistentVolume
metadata:
    name: nfs-test-pv
spec:
    capacity:
      storage: 1Gi
    accessModes:
    -  ReadWriteMany
    storageClassName: nfs
    persistentVolumeReclaimPolicy: Retain
    mountOptions:
        - hard
        - nfsvers=4.1
    nfs:
        path: /mnt/shared
        server: 172.31.28.143
