apiVersion: v1
kind: Pod
metadata:
  name: newdemo
spec:
  volumes:
    - name: volume_encriptado
      persistentVolumeClaim:
        claimName: cte-claim # nome do claim como definido em cte-csi-claim.yaml
  containers:
    - name: ubuntu
      image: ubuntu
      volumeMounts:
        - mountPath: "/data"
          name: test-vol
      command:
        - "sleep"
        - "604800"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
